### ISSUE TITLE
[Bug] Data Product Parser - Failed to register OpenAPI Input Port

### ISSUE THREAD

**Issue by RiccardoAmbrosini** [opendatamesh-initiative/odm-specification-dpdescriptor-parser#5]
# Parser Issue - OpenAPI Input port
While registering a data product to the ODM registry, the server fails to register the data product returning a 500 error.
If one part of the input port declared with OpenAPI is omitted, the data product can be registered. The OpenAPI specification of this port can be validated against the 3.0.1 specification.

## Installation Environment
The registry of ODM is currently deployed on an Azure virtual machine and it is runnining within a Docker container. Version 0.7 is being used.

## Expected Behavior
The data product descriptor should be registered

## Current Behavior
The data product descriptor can only be registered by omitting one of the **response** objects of the second path of the input port, the 200 response.

## Possible Solution
The issue is probably within the IdentityStrategyDefault class within the [Parser folder](https://github.com/opendatamesh-initiative/odm-specification-dpdescriptor-parser/tree/main/src/main/java/org/opendatamesh/dpds/parser)

## Steps to Reproduce
1. Install 0.7 version of the ODM registry.
2. Call the endpoint to register the base version of the data product descriptor (you can use the attached file):
`http://{{registry_url}}:8001/api/v1/pp/registry/products`
3. Call the endpoint to register a new data product version, using as body the attached file:
`http://{{registry_url}}:8001/api/v1/pp/registry/products/{dp-id}/versions`
4. Observe the response, it should be a 500 error like this:
```
o.o.p.p.r.s.c.RegistryExceptionHandler   : java.lang.NullPointerException:Cannot invoke "com.fasterxml.jackson.databind.node.ObjectNode.get(String)" because "schema" is null : Cannot invoke "com.fasterxml.jackson.databind.node.ObjectNode.get(String)" because "schema" is null
```
5. Remove the lines containing the 200 response in the second path (from line 476 through 543).
6. Call the endpoint again and check that the data product gets correctly registered.

To check the validity of the OpenAPI schema, you can use an [online swagger editor](https://editor.swagger.io/) and copy pasting the definition from line 43 to 519.

## Attachments
- Data Product descriptor: [base_dpd.json](https://github.com/user-attachments/files/16373625/base_dpd.json)
- Base Data Product Descriptor: [dps_openapi.json](https://github.com/user-attachments/files/16373626/dps_openapi.json)
- error log: [error.txt](https://github.com/user-attachments/files/16373627/error.txt)

**Comment by gabrielefantini** [comment]
Hi, it seems that the descriptor is parsed correctly with the current version of the parser.
Pay attention that your `Standard Definition Component` have a field named `version` instead of `specificationVersion`.

**Comment by gabrielefantini** [comment]
Hi, I'll try to fix the problem.
In addition, I see that your data product descriptor has the following issues:
- In the `Standard Definition Component`, the `version` field should be named `specificationVersion`
- The version declared (1.0.0) is not the one you are using (3.0.1)
